name: Check Build Issues
on:
  pull_request:
    branches: [ development ]
jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -workspace MovieList.xcodeproj -scheme MovieList -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12'
